[package]
name = "wgpu-native"
version = "0.0.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
	"Noah Charlton <ncharlton002@gmail.com>",
	"Almar Klein <almar@almarklein.org>",
]
edition = "2021"
description = "WebGPU native implementation on gfx-hal"
homepage = "https://github.com/gfx-rs/wgpu-native"
repository = "https://github.com/gfx-rs/wgpu-native"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
default = ["wgsl"]

angle = ["wgc/angle"]
vulkan-portability = ["wgc/vulkan"]
wgsl = ["wgc/wgsl"]
spirv = ["naga/spv-in"]
glsl = ["naga/glsl-in"]
trace = ["wgc/trace"]

[dependencies.wgc]
package = "wgpu-core"
path = "../wgpu/wgpu-core"
features = ["raw-window-handle", "gles"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.wgc]
package = "wgpu-core"
path = "../wgpu/wgpu-core"
features = ["metal"]

[target.'cfg(windows)'.dependencies.wgc]
package = "wgpu-core"
path = "../wgpu/wgpu-core"
features = ["dx11", "dx12"]

[target.'cfg(any(windows, all(unix, not(target_arch = "emscripten"), not(target_os = "ios"), not(target_os = "macos"))))'.dependencies.wgc]
package = "wgpu-core"
path = "../wgpu/wgpu-core"
features = ["vulkan"]

[dependencies.wgt]
package = "wgpu-types"
path = "../wgpu/wgpu-types"

[dependencies.naga]
git = "https://github.com/PyryM/naga"
rev = "7fb3ee52e07c6277c1766cb76c4b4f7078331981"

[dependencies]
lazy_static = "1.4"
raw-window-handle = "0.5"
paste = "1.0"
log = "0.4"
thiserror = "1"

[build-dependencies]
bindgen = "0.63"

[workspace]
resolver = "2"
members = [
	"examples/helper"
]
